# Generated by Django 5.1.3 on 2024-11-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
