# Generated by Django 5.1.3 on 2024-12-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_usuario_delete_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], max_length=50)),
                ('local', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
    ]
