# Generated by Django 5.1.3 on 2024-12-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_evento_descricao_evento_link_evento_palestrantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='palestrantes',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(default='Descrição não fornecida'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_palestrantes', to='agenda.evento')),
            ],
        ),
    ]
