# Generated by Django 5.1.3 on 2024-12-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_evento_local'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Palestrante',
        ),
    ]
