# Generated by Django 5.1.3 on 2024-12-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_delete_palestrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
