# Generated by Django 5.1.3 on 2025-01-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_usuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='usuario_generico', max_length=150, unique=True),
        ),
    ]
