# Generated by Django 5.1.3 on 2025-01-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
