# Generated by Django 5.1.3 on 2025-01-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_alter_evento_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AlterField(
            model_name='evento',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
