# Generated by Django 5.1.3 on 2025-01-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_remove_evento_preco_remove_usuario_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='usuario_generico', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
