# Use a imagem oficial do Node.js como base
FROM node:18-alpine

# Defina o diretório de trabalho no contêiner
WORKDIR /front

# Copie o arquivo de pacotes para o diretório de trabalho
COPY package.json .
COPY package-lock.json .

# Instale as dependências do Node.js
RUN npm install

# Copie o restante do código da aplicação para o diretório de trabalho
COPY . .

# Exponha a porta que o React usará
EXPOSE 3000

# Comando para iniciar o servidor de desenvolvimento React
CMD ["npm", "start"]